POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "jack", "password": "Pass1234!", "email": "jack@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "jack", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json 
Authorization: token c0ef65e7fcf7d8f9089dd7de86d6e41109f8d048